### ISSUE TITLE
Not found io.vertx:vertx-dependencies:pom:4.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by rosell** [reactiverse/reactiverse-junit5-extensions#12]
Hi!

When try to use reactiverse-junit5-web-client or compile this library the maven can not found the snapshot.

**Steps**

- git clone 
- docker run -it --rm --name common-build -v "$HOME/.m2":/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.3-jdk-11-slim mvn clean install

Fail with the next error:

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find io.vertx:vertx-dependencies:pom:4.0.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced @ line 80, column 19
[ERROR] 'dependencies.dependency.version' for io.vertx:vertx-core:jar is missing. @ line 91, column 17
[ERROR] 'dependencies.dependency.version' for io.vertx:vertx-codegen:jar is missing. @ line 96, column 17
[ERROR] 'dependencies.dependency.version' for io.vertx:vertx-docgen:jar is missing. @ line 101, column 17
[ERROR] 'dependencies.dependency.version' for io.vertx:vertx-junit5:jar is missing. @ line 113, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.reactiverse:reactiverse-junit5-extensions-parent:0.2.0-SNAPSHOT (/usr/src/mymaven/pom.xml) has 5 errors
[ERROR]     Non-resolvable import POM: Failure to find io.vertx:vertx-dependencies:pom:4.0.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced @ line 80, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for io.vertx:vertx-core:jar is missing. @ line 91, column 17
[ERROR]     'dependencies.dependency.version' for io.vertx:vertx-codegen:jar is missing. @ line 96, column 17
[ERROR]     'dependencies.dependency.version' for io.vertx:vertx-docgen:jar is missing. @ line 101, column 17
[ERROR]     'dependencies.dependency.version' for io.vertx:vertx-junit5:jar is missing. @ line 113, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by jponge** [comment]
This is because 4.0.0 has been released and snapshots do not exists anymore in the Sonatype snapshots repository.

We need to make a release.

/cc @slinkydeveloper

**Comment by jponge** [comment]
Release in progress, thanks @rosell for reporting!

**Comment by rosell** [comment]
Hi!

I see that you fix the bug, but when the new release 0.3.0 will be available?

**Comment by jponge** [comment]
@slinkydeveloper I did the release using the GH action, but apparently nothing's on Maven Central. Was there anything special to do?

**Comment by rosell** [comment]
Hi!

Sorry, I can not help you because I never publish on Maven central.

**Comment by jponge** [comment]
See #15

**Comment by slinkydeveloper** [comment]
Sorry to answer now, I lost this in the notifs. You need to sync bintray with maven central

**Comment by jponge** [comment]
I'm on it but I got a validation failure already

**Comment by jponge** [comment]
Guess what, Sonatype OSS is slow again tonight

**Comment by jponge** [comment]
https://repo1.maven.org/maven2/io/reactiverse/reactiverse-junit5-web-client/0.3.0/
