### ISSUE TITLE
Only release 0.1.0 is published to maven central and it uses Vertx 4.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by marcpa00** [reactiverse/reactiverse-junit5-extensions#15]
In maven central, there is only one release for reactiverse-junit5-web-client (0.1.0) and that release depends on Vertx 4.0.0-SNAPSHOT.

Having 0.1.0 depends on Vertx 4.0.0-SNAPSHOT seems to be problematic : 

```
Failed to collect dependencies at io.reactiverse:reactiverse-junit5-web-client:jar:0.1.0: Failed to read artifact descriptor for io.reactiverse:reactiverse-junit5-web-client:jar:0.1.0: Could not find artifact io.vertx:vertx-dependencies:pom:4.0.0-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
```

The pom at commit 745b2b8a3684fdeae8a1c36287f68c744cb49d42 solves this, but the 0.3.0 release does not exists.

Has the 0.3.0 release failed somewhat or it is not meant to be released yet ?

**Comment by jponge** [comment]
The release was triggered in CI but somehow nothing appeared.

**Comment by jponge** [comment]
Well it's on Bintray, let me check do perform a synchronizartion

**Comment by jponge** [comment]
It's available now, thanks for pinging!

https://repo1.maven.org/maven2/io/reactiverse/reactiverse-junit5-web-client/0.3.0/
