### ISSUE TITLE
testRequest doesn't respect ports, just uses default web client port which is 80, also should have an overload for any URL instead of just path

### ISSUE THREAD

**Issue by doctorpangloss** [reactiverse/reactiverse-junit5-extensions#4]
https://github.com/reactiverse/reactiverse-junit5-extensions/blob/a7e53a66a5ebb1aa5b270e27a717cca7c9e11736/reactiverse-junit5-web-client/src/main/java/io/reactiverse/junit5/web/TestRequest.java#L306

**Comment by slinkydeveloper** [comment]
Because we perform asserts in fact on responses, what if we remove the signatures that creates the requests? I don't want to clone the APIs of web client in `TestRequest`. Does that makes sense to you?

**Comment by doctorpangloss** [comment]
I think I worked around this by just not using `testRequest`.

**Comment by slinkydeveloper** [comment]
DYM not using this module at all?
