### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by aesteve** [reactiverse/reactiverse-junit5-extensions#5]
For people using `vertx-junit5` what should they change? What are maven central coordinates?

**Comment by jponge** [comment]
The `README` lacks a repeat of the `groupId` which we should add.

Other than that I think no 3.9 release had officially the classes here, @slinkydeveloper do you confirm?

**Comment by aesteve** [comment]
In fact it happened while migrating tests that were working with 4.0.0-milestone4 to 4.0.0.Beta3.

**Comment by aesteve** [comment]
for ref. https://search.maven.org/search?q=reactiverse

**Comment by jponge** [comment]
@aesteve what broke exactly?

**Comment by aesteve** [comment]
https://github.com/aesteve/reproducers-4-0-0-beta/blob/main/src/test/kotlin/com/github/aesteve/reproducers/RxVertxNotWorking.kt

**Comment by jponge** [comment]
Ah ok so this might not be the module you expected, the new RxJava support has been moved to https://github.com/vert-x3/vertx-rx/tree/master/rx-junit5-providers

**Comment by jponge** [comment]
@aesteve see https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes#vertx-junit5

**Comment by slinkydeveloper** [comment]
@jponge yeah i still didn't worked on the releases of this module, tbh i don't know where to start from. Do we have any guideline on publishing reactiverse packages or everybody is on his/her own?

**Comment by aesteve** [comment]
https://github.com/reactiverse/aws-sdk may help

New tags are published to jCenter, then sync to central has to be made
manually.

**Comment by jponge** [comment]
Yes you can either automate this on the CI/CD side, or just do it manually. Up to you really.

**Comment by slinkydeveloper** [comment]
The module is release, it's on maven central :partying_face:
